
spring:
  data:
    mongodb:
      database: discord-github-melder
      auto-index-creation: true
      host: ${mongo.host}
      username: ${mongo.username}
      password: ${mongo.password}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github.client-id}
            client-secret: ${github.client-secret}
            scope:
              - read:user

logging:
  group:
    app:
      - me.itzg.melderbot
    # https://docs.discord4j.com/logging/#available-loggers
    discord4j:
      - discord4j.rest.request
      - discord4j.gateway