<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Discord Github Melder</title>
  <link rel="stylesheet" href="/css/main.css"/>
</head>
<body>
<main>
  <h1>Discord Github Melder</h1>

  <p>
    Use the <code>/meld link-with-github</code> command to make use of this bot.
  </p>

  <div class="callout">
    <div class="content">
      <p>
        <a target="_blank" href="https://github.com/itzg/discord-github-melder-bot#installation">
          Follow these instructions</a>
        to run this bot on your own Discord servers.
      </p>
      <p>
        <a href="https://github.com/itzg/discord-github-melder-bot/issues" target="_blank">
          Click here</a>
        to report issues.
      </p>
    </div>
  </div>

</main>

</body>
</html>