name: "Build image"
on:
  push:
    branches:
      - main
      - "test/**"
    tags:
      - "\d+.\d+.\d+"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle build and push
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -PimageRepo=ghcr.io/itzg
            -PimagePlatforms=linux/amd64,linux/arm64
            -PimagePush=true 
            -PimageCacheFrom=type=gha
            -PimageCacheTo=type=gha,mode=max
            buildSimpleBootImage

