name: "Build image"
on:
  push:
    branches:
      - main
      - "test/**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/simple-boot-image-to-ghcr.yml@main
    with:
      image-repo: "ghcr.io/itzg"
      image-platforms: "linux/amd64,linux/arm64"
      extra-gradle-tasks: test