name: "Build image"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Setup
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Gradle build
        id: gradleBuild
        run: gradle build outputJarForGha

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            itzg/discord-github-melder-bot
          flavor: |
            latest=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Image build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            JAR_FILE=${{ steps.gradleBuild.outputs.jar }}
          tags: ${{ steps.meta.outputs.tags }}
          # ensure latest base image is used
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
