name: Validate PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  test:
    uses: itzg/github-workflows/.github/workflows/gradle-build.yml@main
    with:
      arguments: test
      include-test-report: true